import type {
  Discount,
  InventoryAdjustment,
  Order,
  OrderRefund,
  Product,
  ProductCollection,
  ProductVariant,
  ShippingZone,
  Store,
} from "@/features/commerce/types";

export const mockStores: Store[] = [
  {
    id: "demo-store-outdoor",
    ownerId: "demo_user_zendora",
    name: "Northline Supply",
    slug: "northline-supply",
    description:
      "A calm, focused storefront for founders selling premium everyday goods.",
    currency: "USD",
    themeColor: "#0f766e",
    status: "active",
    createdAt: "2026-04-12T10:00:00.000Z",
    productCount: 4,
    orderCount: 3,
    revenueCents: 53497,
    inventoryCount: 142,
    shippingRateCents: 799,
    freeShippingThresholdCents: 15000,
    taxRateBps: 825,
  },
  {
    id: "demo-store-studio",
    ownerId: "demo_user_zendora",
    name: "Aster Studio",
    slug: "aster-studio",
    description:
      "A draft store for testing multiple brands under the same merchant account.",
    currency: "USD",
    themeColor: "#0284c7",
    status: "draft",
    createdAt: "2026-05-08T09:30:00.000Z",
    productCount: 2,
    orderCount: 0,
    revenueCents: 0,
    inventoryCount: 56,
    shippingRateCents: 599,
    freeShippingThresholdCents: 10000,
    taxRateBps: 0,
  },
];

export const mockShippingZones: ShippingZone[] = [
  {
    id: "demo-shipping-zone-us",
    storeId: "demo-store-outdoor",
    name: "United States",
    countries: ["United States", "US", "USA"],
    rateCents: 799,
    freeShippingThresholdCents: 15000,
    status: "active",
    createdAt: "2026-04-13T10:00:00.000Z",
  },
  {
    id: "demo-shipping-zone-ca-eu",
    storeId: "demo-store-outdoor",
    name: "Canada and Europe",
    countries: ["Canada", "CA", "United Kingdom", "UK", "Germany", "France"],
    rateCents: 2499,
    freeShippingThresholdCents: 30000,
    status: "active",
    createdAt: "2026-04-13T10:05:00.000Z",
  },
  {
    id: "demo-shipping-zone-studio-us",
    storeId: "demo-store-studio",
    name: "US draft rate",
    countries: ["United States", "US"],
    rateCents: 599,
    freeShippingThresholdCents: 10000,
    status: "active",
    createdAt: "2026-05-08T10:00:00.000Z",
  },
];

export const mockProductVariants: ProductVariant[] = [
  {
    id: "demo-variant-carry-pack-forest",
    storeId: "demo-store-outdoor",
    productId: "demo-product-carry-pack",
    optionName: "Color",
    optionValue: "Forest",
    sku: "NLS-BAG-001-FOR",
    priceCents: 12900,
    currency: "USD",
    inventoryCount: 14,
    status: "active",
    sortOrder: 1,
    createdAt: "2026-04-14T10:00:00.000Z",
  },
  {
    id: "demo-variant-carry-pack-clay",
    storeId: "demo-store-outdoor",
    productId: "demo-product-carry-pack",
    optionName: "Color",
    optionValue: "Clay",
    sku: "NLS-BAG-001-CLA",
    priceCents: 13900,
    currency: "USD",
    inventoryCount: 18,
    status: "active",
    sortOrder: 2,
    createdAt: "2026-04-14T10:05:00.000Z",
  },
  {
    id: "demo-variant-hydra-bottle-steel",
    storeId: "demo-store-outdoor",
    productId: "demo-product-hydra-bottle",
    optionName: "Color",
    optionValue: "Brushed steel",
    sku: "NLS-BOT-003-STL",
    priceCents: 4200,
    currency: "USD",
    inventoryCount: 4,
    status: "active",
    sortOrder: 1,
    createdAt: "2026-04-18T10:00:00.000Z",
  },
  {
    id: "demo-variant-hydra-bottle-onyx",
    storeId: "demo-store-outdoor",
    productId: "demo-product-hydra-bottle",
    optionName: "Color",
    optionValue: "Onyx",
    sku: "NLS-BOT-003-ONX",
    priceCents: 4600,
    currency: "USD",
    inventoryCount: 2,
    status: "active",
    sortOrder: 2,
    createdAt: "2026-04-18T10:05:00.000Z",
  },
  {
    id: "demo-variant-sprint-shoe-8",
    storeId: "demo-store-outdoor",
    productId: "demo-product-sprint-shoe",
    optionName: "Size",
    optionValue: "8",
    sku: "NLS-SHO-004-08",
    priceCents: 9800,
    currency: "USD",
    inventoryCount: 30,
    status: "active",
    sortOrder: 1,
    createdAt: "2026-04-22T10:00:00.000Z",
  },
  {
    id: "demo-variant-sprint-shoe-9",
    storeId: "demo-store-outdoor",
    productId: "demo-product-sprint-shoe",
    optionName: "Size",
    optionValue: "9",
    sku: "NLS-SHO-004-09",
    priceCents: 9800,
    currency: "USD",
    inventoryCount: 34,
    status: "active",
    sortOrder: 2,
    createdAt: "2026-04-22T10:05:00.000Z",
  },
  {
    id: "demo-variant-sprint-shoe-10",
    storeId: "demo-store-outdoor",
    productId: "demo-product-sprint-shoe",
    optionName: "Size",
    optionValue: "10",
    sku: "NLS-SHO-004-10",
    priceCents: 9800,
    currency: "USD",
    inventoryCount: 29,
    status: "active",
    sortOrder: 3,
    createdAt: "2026-04-22T10:10:00.000Z",
  },
];

export const mockProducts: Product[] = [
  {
    id: "demo-product-carry-pack",
    storeId: "demo-store-outdoor",
    name: "Field Carry Pack",
    slug: "field-carry-pack",
    sku: "NLS-BAG-001",
    category: "Bags",
    description:
      "Weather-resistant day pack with a structured laptop sleeve and clean travel pockets.",
    priceCents: 12900,
    currency: "USD",
    inventoryCount: 32,
    imageUrl:
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    status: "active",
    createdAt: "2026-04-14T10:00:00.000Z",
    variants: mockProductVariants.filter(
      (variant) => variant.productId === "demo-product-carry-pack",
    ),
  },
  {
    id: "demo-product-trail-watch",
    storeId: "demo-store-outdoor",
    name: "Trail Watch",
    slug: "trail-watch",
    sku: "NLS-WAT-002",
    category: "Accessories",
    description:
      "Low-profile field watch with sapphire glass, quick-release strap, and 10 ATM rating.",
    priceCents: 21900,
    currency: "USD",
    inventoryCount: 11,
    imageUrl:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    status: "active",
    createdAt: "2026-04-16T10:00:00.000Z",
    variants: [],
  },
  {
    id: "demo-product-hydra-bottle",
    storeId: "demo-store-outdoor",
    name: "Hydra Bottle",
    slug: "hydra-bottle",
    sku: "NLS-BOT-003",
    category: "Drinkware",
    description:
      "Insulated stainless bottle with a soft-touch finish and leakproof carry loop.",
    priceCents: 4200,
    currency: "USD",
    inventoryCount: 6,
    imageUrl:
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1200&q=80",
    status: "active",
    createdAt: "2026-04-18T10:00:00.000Z",
    variants: mockProductVariants.filter(
      (variant) => variant.productId === "demo-product-hydra-bottle",
    ),
  },
  {
    id: "demo-product-sprint-shoe",
    storeId: "demo-store-outdoor",
    name: "Sprint Shoe",
    slug: "sprint-shoe",
    sku: "NLS-SHO-004",
    category: "Footwear",
    description:
      "A lightweight trainer with breathable mesh and a responsive everyday midsole.",
    priceCents: 9800,
    currency: "USD",
    inventoryCount: 93,
    imageUrl:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
    status: "active",
    createdAt: "2026-04-22T10:00:00.000Z",
    variants: mockProductVariants.filter(
      (variant) => variant.productId === "demo-product-sprint-shoe",
    ),
  },
  {
    id: "demo-product-calm-lamp",
    storeId: "demo-store-studio",
    name: "Calm Desk Lamp",
    slug: "calm-desk-lamp",
    sku: "AST-LMP-001",
    category: "Lighting",
    description: "A warm desk lamp designed for tiny workspaces.",
    priceCents: 7600,
    currency: "USD",
    inventoryCount: 18,
    imageUrl:
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80",
    status: "draft",
    createdAt: "2026-05-09T10:00:00.000Z",
    variants: [],
  },
  {
    id: "demo-product-ceramic-cup",
    storeId: "demo-store-studio",
    name: "Studio Ceramic Cup",
    slug: "studio-ceramic-cup",
    sku: "AST-CUP-002",
    category: "Drinkware",
    description: "Hand-finished cup for coffee, tea, and late product reviews.",
    priceCents: 2800,
    currency: "USD",
    inventoryCount: 38,
    imageUrl:
      "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=1200&q=80",
    status: "draft",
    createdAt: "2026-05-10T10:00:00.000Z",
    variants: [],
  },
];

export const mockCollections: ProductCollection[] = [
  {
    id: "demo-collection-everyday-carry",
    storeId: "demo-store-outdoor",
    title: "Everyday Carry",
    slug: "everyday-carry",
    description:
      "Bags, bottles, and accessories built for commutes, travel days, and daily work.",
    imageUrl:
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    status: "active",
    sortOrder: 1,
    productIds: [
      "demo-product-carry-pack",
      "demo-product-hydra-bottle",
      "demo-product-trail-watch",
    ],
    productCount: 3,
    createdAt: "2026-04-24T10:00:00.000Z",
  },
  {
    id: "demo-collection-trail-ready",
    storeId: "demo-store-outdoor",
    title: "Trail Ready",
    slug: "trail-ready",
    description:
      "Lightweight pieces for weekend hikes, training runs, and fast weather shifts.",
    imageUrl:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
    status: "active",
    sortOrder: 2,
    productIds: [
      "demo-product-sprint-shoe",
      "demo-product-trail-watch",
      "demo-product-hydra-bottle",
    ],
    productCount: 3,
    createdAt: "2026-04-25T10:00:00.000Z",
  },
  {
    id: "demo-collection-studio-desk",
    storeId: "demo-store-studio",
    title: "Studio Desk",
    slug: "studio-desk",
    description: "Draft desk goods for the studio storefront.",
    status: "draft",
    sortOrder: 1,
    productIds: ["demo-product-calm-lamp", "demo-product-ceramic-cup"],
    productCount: 2,
    createdAt: "2026-05-12T10:00:00.000Z",
  },
];

export const mockOrders: Order[] = [
  {
    id: "demo-order-1001",
    storeId: "demo-store-outdoor",
    customerName: "Mira Chen",
    customerEmail: "mira@example.com",
    customerPhone: "+1 555 0191",
    shippingAddress: {
      line1: "121 Commerce Street",
      line2: "Suite 4B",
      city: "Austin",
      region: "TX",
      postalCode: "78701",
      country: "United States",
    },
    customerNote: "Leave at the front desk.",
    status: "paid",
    source: "storefront",
    paymentStatus: "paid",
    paymentMethod: "card",
    paymentProvider: "Manual card",
    paymentReference: "CARD-1001",
    subtotalCents: 34800,
    discountCents: 0,
    shippingCents: 0,
    taxCents: 2871,
    taxRateBps: 825,
    totalCents: 37671,
    refundedCents: 0,
    refundableCents: 37671,
    currency: "USD",
    createdAt: "2026-05-25T13:20:00.000Z",
    paidAt: "2026-05-25T13:22:00.000Z",
    items: [
      {
        id: "demo-order-item-1001-1",
        orderId: "demo-order-1001",
        productId: "demo-product-trail-watch",
        productName: "Trail Watch",
        unitPriceCents: 21900,
        quantity: 1,
        createdAt: "2026-05-25T13:20:00.000Z",
      },
      {
        id: "demo-order-item-1001-2",
        orderId: "demo-order-1001",
        productId: "demo-product-carry-pack",
        productVariantId: "demo-variant-carry-pack-forest",
        productName: "Field Carry Pack",
        variantName: "Color: Forest",
        variantSku: "NLS-BAG-001-FOR",
        unitPriceCents: 12900,
        quantity: 1,
        createdAt: "2026-05-25T13:20:00.000Z",
      },
    ],
    refunds: [],
  },
  {
    id: "demo-order-1002",
    storeId: "demo-store-outdoor",
    customerName: "Ari Patel",
    customerEmail: "ari@example.com",
    customerPhone: "+1 555 0184",
    shippingAddress: {
      line1: "88 Market Avenue",
      city: "Portland",
      region: "OR",
      postalCode: "97205",
      country: "United States",
    },
    status: "fulfilled",
    source: "storefront",
    paymentStatus: "partially_refunded",
    paymentMethod: "bank_transfer",
    paymentProvider: "Bank transfer",
    paymentReference: "ACH-1002",
    subtotalCents: 18500,
    discountCents: 0,
    shippingCents: 0,
    taxCents: 1526,
    taxRateBps: 825,
    totalCents: 20026,
    refundedCents: 4200,
    refundableCents: 15826,
    currency: "USD",
    createdAt: "2026-05-29T09:40:00.000Z",
    paidAt: "2026-05-29T09:42:00.000Z",
    fulfilledAt: "2026-05-30T14:15:00.000Z",
    trackingCarrier: "UPS",
    trackingNumber: "1Z999AA10123456784",
    trackingUrl: "https://www.ups.com/track",
    fulfillmentNote: "Packed in one carton with recycled fill.",
    items: [
      {
        id: "demo-order-item-1002-1",
        orderId: "demo-order-1002",
        productId: "demo-product-hydra-bottle",
        productVariantId: "demo-variant-hydra-bottle-onyx",
        productName: "Hydra Bottle",
        variantName: "Color: Onyx",
        variantSku: "NLS-BOT-003-ONX",
        unitPriceCents: 4600,
        quantity: 1,
        createdAt: "2026-05-29T09:40:00.000Z",
      },
      {
        id: "demo-order-item-1002-2",
        orderId: "demo-order-1002",
        productId: "demo-product-carry-pack",
        productVariantId: "demo-variant-carry-pack-clay",
        productName: "Field Carry Pack",
        variantName: "Color: Clay",
        variantSku: "NLS-BAG-001-CLA",
        unitPriceCents: 13900,
        quantity: 1,
        createdAt: "2026-05-29T09:40:00.000Z",
      },
    ],
    refunds: [
      {
        id: "demo-refund-1002-1",
        storeId: "demo-store-outdoor",
        orderId: "demo-order-1002",
        clerkUserId: "demo_user_zendora",
        amountCents: 4200,
        reason: "customer_request",
        note: "Bottle returned unopened after duplicate purchase.",
        restockedInventory: false,
        createdAt: "2026-06-01T11:20:00.000Z",
      },
    ],
  },
  {
    id: "demo-order-1003",
    storeId: "demo-store-outdoor",
    customerName: "Sam Rivera",
    customerEmail: "sam@example.com",
    shippingAddress: {
      line1: "240 Harbor Road",
      city: "San Diego",
      region: "CA",
      postalCode: "92101",
      country: "United States",
    },
    status: "pending",
    source: "manual",
    internalNote: "Manual phone order; send invoice follow-up before packing.",
    paymentStatus: "pending",
    paymentMethod: "manual_invoice",
    paymentProvider: "manual",
    paymentReference: "INV-1003",
    subtotalCents: 12900,
    discountCode: "WELCOME10",
    discountCents: 1290,
    shippingCents: 799,
    taxCents: 958,
    taxRateBps: 825,
    totalCents: 13367,
    refundedCents: 0,
    refundableCents: 13367,
    currency: "USD",
    createdAt: "2026-06-02T16:12:00.000Z",
    items: [
      {
        id: "demo-order-item-1003-1",
        orderId: "demo-order-1003",
        productId: "demo-product-carry-pack",
        productVariantId: "demo-variant-carry-pack-forest",
        productName: "Field Carry Pack",
        variantName: "Color: Forest",
        variantSku: "NLS-BAG-001-FOR",
        unitPriceCents: 12900,
        quantity: 1,
        createdAt: "2026-06-02T16:12:00.000Z",
      },
    ],
    refunds: [],
  },
];

export const mockOrderRefunds: OrderRefund[] = mockOrders.flatMap(
  (order) => order.refunds,
);

export const mockInventoryAdjustments: InventoryAdjustment[] = [
  {
    id: "demo-inventory-adjustment-1001",
    storeId: "demo-store-outdoor",
    productId: "demo-product-carry-pack",
    clerkUserId: "demo_user_zendora",
    reason: "restock",
    reference: "PO-1042",
    note: "Spring replenishment received.",
    delta: 24,
    previousInventory: 8,
    nextInventory: 32,
    createdAt: "2026-05-20T10:30:00.000Z",
  },
  {
    id: "demo-inventory-adjustment-1002",
    storeId: "demo-store-outdoor",
    productId: "demo-product-hydra-bottle",
    clerkUserId: "demo_user_zendora",
    reason: "damage",
    reference: "QC-882",
    note: "Two bottles removed after inspection.",
    delta: -2,
    previousInventory: 8,
    nextInventory: 6,
    createdAt: "2026-05-27T15:45:00.000Z",
  },
  {
    id: "demo-inventory-adjustment-1003",
    storeId: "demo-store-outdoor",
    productId: "demo-product-trail-watch",
    clerkUserId: "demo_user_zendora",
    reason: "correction",
    reference: "Cycle count",
    delta: -1,
    previousInventory: 12,
    nextInventory: 11,
    createdAt: "2026-06-01T09:10:00.000Z",
  },
];

export const mockDiscounts: Discount[] = [
  {
    id: "demo-discount-welcome10",
    storeId: "demo-store-outdoor",
    code: "WELCOME10",
    type: "percent",
    value: 10,
    minSubtotalCents: 5000,
    usageLimit: 100,
    redemptionCount: 12,
    status: "active",
    createdAt: "2026-05-01T10:00:00.000Z",
  },
  {
    id: "demo-discount-pack15",
    storeId: "demo-store-outdoor",
    code: "PACK15",
    type: "fixed",
    value: 1500,
    minSubtotalCents: 15000,
    redemptionCount: 4,
    status: "paused",
    createdAt: "2026-05-18T10:00:00.000Z",
  },
];
